# **TOPIC 1**
Write a program to input a floating number from keyboard and do the following things: 
-	A. The input number must have meaningful decimal part. If not, ask input again.
-	B. Separate number into two lists. The first list contains integer part and the second list contains decimal part

In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Input number
# A
while True:
    try:
        strnumber = input('Input floating number:')
        if float(strnumber) == int(float(strnumber)):
            print('Wrong format, please reinput.')
            continue
        if str(np.round(float(strnumber),decimals = 15)) == strnumber:
            break
    except ValueError as e:
        print('Error found:', e)
        print('Please, reinput')
#B
Intstr = strnumber.split('.')[0].split('-')[-1]
Decstr = strnumber.split('.')[1]
IntList = [int(i) for i in Intstr]
DecList = [int(i) for i in Decstr]
print('Input =', strnumber)
print('IntList =', IntList)
print('DecList =', DecList)

Input floating number:-315.7542
Input = -315.7542
IntList = [3, 1, 5]
DecList = [7, 5, 4, 2]

# **TOPIC 2**
Write a program to input three element : a string and two numbers. Then, do the following things: 
-	A.The string input must be in List [“GCD”, “LCM”, “FRAC”] and two number must be positive integer numbers. If not, ask input again. 
-	B.Check the string if : GCD  ==> Calculate greatest common divisor of two numbers, LCM ==> Calculate lowest common multiple of two numbers, FRAC ==> Reduce the fraction a/b

In [3]:
import numpy as np
from fractions import Fraction

In [4]:
#A
options = ['GCD', 'LCM', 'FRAC']
while True:
    option = input("Input your option, it must be one of ['GCD', 'LCM', 'FRAC']: ")
    if option in options: break
while True:
    try:
        a = input('Please input the first positive interger:')
        b = input('Please input the second positive interger:')
        if not(float(b) == int(float(b)) and float(a) == int(float(a))) or int(a) <= 0 or int(b) <= 0:
            print('You must input postive interger, please reinput')
            continue
    except ValueError as e:
        print('Error found:', e)
        print('Please, reinput')
    else: break
if option == 'GCD':
    result = np.gcd(int(a),int(b))
if option == 'LCM':
    result = np.lcm(int(a),int(b))
if option == 'FRAC':
    result = Fraction(int(a),int(b))
print(f'Calculating {option} of {a} and {b} equal:', result)

Input your option, it must be one of ['GCD', 'LCM', 'FRAC']: FRAC
Please input the first positive interger:754
Please input the second positive interger:428
Calculating FRAC of 754 and 428 equal: 377/214

# **TOPIC 3**
Read the csv file “BigMartSales Prediction/train.csv” (Lesson 02) into a dataframe and do the following things:
-	A. Write a function to input name of statistics measurement and an attribute column and return the statistical value
-	B.Write a function to input a List of Conditions and a List of Logic Operators and return a sub dataframe after querying

In [5]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
file = 'D:/Python For AI/AI/BigMartSales Prediction/Train.csv'
BigMartSalesDF = pd.read_csv(file)
BigMartSalesDF.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [7]:
print('Describe table of object in Dataframe')
BigMartSalesDF.describe(include=[object])
print('\nDescribe table of number in Dataframe')
BigMartSalesDF.describe(include=[np.number])

Describe table of object in Dataframe

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
count,8523,8523,8523,8523,6113,8523,8523
unique,1559,5,16,10,3,3,4
top,FDG33,Low Fat,Fruits and Vegetables,OUT027,Medium,Tier 3,Supermarket Type1
freq,10,5089,1232,935,2793,3350,5577

Describe table of number in Dataframe

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [8]:
#A
def StatisticInfo(method, feature, data = BigMartSalesDF):
    methods = {'count':lambda x: x.count(), 'mean':lambda x: x.mean(), 'std':lambda x: x.std(), 'min':lambda x: x.min(), 
    'max':lambda x: x.max(), 'unique':lambda x: x.unique(), 'mode':lambda x: x.mode(), 'median':lambda x: x.median()}
    try:
        return methods[method](data[feature])
    except:
        print(f"This column don't have {method} statistics measurement")

In [9]:
Statisticlist = ['count', 'mean', 'std', 'min', 'max', 'unique', 'mode', 'median']
while True:
    print('Input statistics measurement, it should be one of those in the below list:')
    print(Statisticlist)
    method = input()
    print()
    if method in Statisticlist: break
while True:
    print("Input column's name, it should be one of those in the below list:")
    print(list(BigMartSalesDF.columns))
    feature = input()
    print()
    if feature in BigMartSalesDF.columns: break
print(f'The {method} of {feature} is:\n{StatisticInfo(method,feature)}')

Input statistics measurement, it should be one of those in the below list:
['count', 'mean', 'std', 'min', 'max', 'unique', 'mode', 'median']
unique

Input column's name, it should be one of those in the below list:
['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type', 'Item_MRP', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type', 'Item_Outlet_Sales']
Outlet_Type

The unique of Outlet_Type is:
['Supermarket Type1' 'Supermarket Type2' 'Grocery Store'
 'Supermarket Type3']

In [10]:
#B
def Query(conditionlist, operatorlist, data = BigMartSalesDF):
    try:
        if len(conditionlist) - len(operatorlist) != 1:
            print('Sorry, wrong input')
        else:
            operatorlist = [i.lower() for i in operatorlist]
            operator = {'and':lambda x,y:x & y, 'or':lambda x,y:x | y}
            filter = operator[operatorlist[0]](conditionlist[0],conditionlist[1])
            for i in range(1,len(operatorlist)):
                filter = operator[operatorlist[i]](conditionlist[i+1],filter)
            return data[filter]
    except:
        print('Sorry, wrong input')

In [11]:
condi1 = BigMartSalesDF['Item_Weight'] < 10
condi2 = BigMartSalesDF['Item_Fat_Content'] == 'Low Fat'
condi3 = BigMartSalesDF['Item_Type'] == 'Fruits and Vegetables'
QueryDF = Query([condi1, condi2, condi3], ['AND', 'AND'])
display(QueryDF.head(8))

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
86,FDZ55,6.055,Low Fat,0.025404,Fruits and Vegetables,160.9920,OUT035,2004,Small,Tier 2,Supermarket Type1,2716.4640
138,FDX44,9.300,Low Fat,0.043210,Fruits and Vegetables,90.8172,OUT017,2007,NaN,Tier 2,Supermarket Type1,535.3032
154,FDX20,7.365,Low Fat,0.042560,Fruits and Vegetables,226.1720,OUT046,1997,Small,Tier 1,Supermarket Type1,3169.2080
252,FDV32,7.785,Low Fat,0.088846,Fruits and Vegetables,61.4510,OUT049,1999,Medium,Tier 1,Supermarket Type1,759.0120
272,FDQ56,6.590,Low Fat,0.105509,Fruits and Vegetables,85.6908,OUT013,1987,High,Tier 3,Supermarket Type1,1929.4884
306,FDB21,7.475,Low Fat,0.148822,Fruits and Vegetables,241.2854,OUT045,2002,NaN,Tier 2,Supermarket Type1,5317.0788
365,FDG45,8.100,Low Fat,0.127930,Fruits and Vegetables,211.4902,OUT013,1987,High,Tier 3,Supermarket Type1,3610.6334
391,FDY32,7.605,Low Fat,0.129503,Fruits and Vegetables,164.0210,OUT045,2002,NaN,Tier 2,Supermarket Type1,3914.9040